### ISSUE TITLE
galleria rotates a picture to landscape when switching to fullscreen

### ISSUE THREAD

**Issue by anarcat** [saimn/sigal#279]
There's something really odd with a picture I have. Some other pictures of mine don't have that problem, but for some reason, when I switch to fullscreen in galleria with this special picture, it gets flipped as landscape even though it was displayed, properly, in portrait mode, when in normal mode.

Worse: when I go back from fullscreen, the image is still squeeze to the side, like this:

![snap-2017 12 29-22 57 14](https://user-images.githubusercontent.com/796623/34451185-b04e7ea6-ecec-11e7-9af8-3bd73a65a9bb.png)

It's as if something inside galleria was flipping the image. This happens only when I have `keep_orig` enabled, here's the (minimal) config to reproduce this:

```
theme = 'galleria'
autorotate_images = True
copy_exif_data = False
keep_orig = True
```

I do not have consent to publish the image, so I would prefer if I could send you a sample in private.

Other themes do not seem to have that problem. Setting `keep_orig` to `False` works around the issue as well. I can reproduce this in Firefox 57 and Chromium 63.0.3239.84.

**Comment by anarcat** [comment]
interestingly, `use_orig` has no effect: when galleria flips to fullscreen, sigal tells it to load the `original` file, and that breaks the rotation immediately.

**Comment by anarcat** [comment]
and obviously, i can't reproduce this now anymore. Not sure what was going on with that picture, but sorry for the noise. :/

**Comment by saimn** [comment]
Hmm weird that this happens only in fullscreen. The image rotation stuff is confusing, but as long as Pillow does not allow to modify the exif after rotation (#72) there is no good solution.

**Comment by anarcat** [comment]
yeah this is just totally weird, especially since i can't reproduce anymore. i wonder if there could have been some caching issues...

i'll bump this again if i have the problem again later.

**Comment by anarcat** [comment]
oh and just another thought i had... one thing with image rotation is that browsers *do* know how to rotate images on their own. a portrait photo *will* get displayed vertically if opened directly (ie. not inlined in a `<img>` tag but directly loaded in the browser) *but* will be displayed sideways if inlined. it's super weird, and it could be what was happening here - maybe the original was being loaded when going to fullscreen, and then still used when popping back out of there....

**Comment by anarcat** [comment]
okay well, this damn bug is back. and now i have public photos to show it, which might make things easier here...

https://photos.anarc.at/cities/montreal/#/3

Note that this photos is fine:

https://photos.anarc.at/cities/montreal/#/4

The difference? The latter was exported by Darktable, while the former is straight from the camera... Could this be why there is a problem here? That pillow wouldn't detect the proper exif tags from the camera?

**Comment by saimn** [comment]
I see both with the correct (vertical) orientation

**Comment by anarcat** [comment]
even in full screen?

**Comment by anarcat** [comment]
here's a [screencast](https://github.com/saimn/sigal/files/1709305/screencast.zip) (zip file because github doesn't support video!) of the problem from my point of view, just to make sure we're on the same page. this is `Build identifier: Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0`.

**Comment by saimn** [comment]
Ok, I can also see this actually, but I need to wait long enough because my network is slow and the files are big and galleria shows the low res file while it downloads the high res! So maybe an issue with the fullscreen plugin ? It would be interesting to check in galleria's changelog or git repo is there is something. I think there is more recent versions than the one bundled in sigal, but last time I tried to update the design was broken.

**Comment by anarcat** [comment]
yeah, i was wondering if this could be solved by a theme update as well... i can't imagine that galleria has such a huge bug and no one noticed (although I did look at their issue queue, iirc and couldn't find anything)...

**Comment by anarcat** [comment]
yeah, i was wondering if this could be solved by a theme update as well... i can't imagine that galleria has such a huge bug and no one noticed (although I did look at their issue queue, iirc and couldn't find anything)... my strategy right now is to wait for theme updates in sigal and try again :)

**Comment by saimn** [comment]
You're lucky, I pushed a branch with the theme update yesterday, and I just merged it (#296) :)

**Comment by anarcat** [comment]
nice, i guess i need to try this out now!

**Comment by anarcat** [comment]
at first glance, this seems fixed in 1.4.0 - thanks!!!

**Comment by saimn** [comment]
Good news! :)

**Comment by anarcat** [comment]
hmm... unfortunately, it seems I am still seeing this bug in 1.4.0, sorry for the false positive. :( it does not seem like Galleria 1.5.7 fixed the problem and i still see originals rotate all over the place...
